use super::*;

pub(super) fn decode_line_height(value: i64) -> String {
    match value {
        0 => "variable".to_string(),
        1 => "auto".to_string(),
        _ => fmt_num(value as f64 / 20.0),
    }
}

pub(super) fn encode_line_height(value: &str, unsigned: bool) -> Option<Vec<u8>> {
    let numeric = match value.trim().to_ascii_lowercase().as_str() {
        "variable" => 0,
        "auto" => 1,
        value => (value.parse::<f64>().ok()? * 20.0).round() as i32,
    };
    if unsigned {
        Some(u16::try_from(numeric).ok()?.to_le_bytes().to_vec())
    } else {
        Some(i16::try_from(numeric).ok()?.to_le_bytes().to_vec())
    }
}

pub(super) fn property_schema(tag: u16) -> Option<PropertySchema> {
    let schema = match tag {
        0x0001 => ("CreationUserName", PropertyKind::String),
        0x0003 => ("CreationProgram", PropertyKind::String),
        0x0004 => ("ModificationUserName", PropertyKind::String),
        0x0006 => ("ModificationProgram", PropertyKind::String),
        0x0008 => ("Name", PropertyKind::String),
        0x0009 => ("Comment", PropertyKind::String),
        0x000A => ("Z", PropertyKind::Int16),
        0x0011 => ("Visible", PropertyKind::Boolean),
        0x0012 | 0x0013 => ("SupersededBy", PropertyKind::UInt32),
        0x0200 => ("p", PropertyKind::Point2D),
        0x0201 => ("xyz", PropertyKind::Point3D),
        0x0202 => ("extent", PropertyKind::Point2D),
        0x0204 => ("BoundingBox", PropertyKind::Rectangle),
        0x0205 => ("RotationAngle", PropertyKind::Fixed16_16),
        0x0207 => ("Head3D", PropertyKind::Point3D),
        0x0208 => ("Tail3D", PropertyKind::Point3D),
        0x0209 => ("TopLeft", PropertyKind::Point2D),
        0x020A => ("TopRight", PropertyKind::Point2D),
        0x020B => ("BottomRight", PropertyKind::Point2D),
        0x020C => ("BottomLeft", PropertyKind::Point2D),
        0x020D => ("Center3D", PropertyKind::Point3D),
        0x020E => ("MajorAxisEnd3D", PropertyKind::Point3D),
        0x020F => ("MinorAxisEnd3D", PropertyKind::Point3D),
        0x0301 => ("color", PropertyKind::UInt16),
        0x0302 => ("bgcolor", PropertyKind::Int16),
        0x0400 => ("NodeType", PropertyKind::Enum(NODE_TYPE)),
        0x0401 => ("LabelDisplay", PropertyKind::Enum8(LABEL_DISPLAY)),
        0x0402 => ("Element", PropertyKind::Int16),
        0x0420 => ("Isotope", PropertyKind::Int16),
        0x0421 => ("Charge", PropertyKind::Int8),
        0x0422 => ("Radical", PropertyKind::Enum8(ATOM_RADICAL)),
        0x0424 => ("ImplicitHydrogens", PropertyKind::BooleanImplied),
        0x042B => ("NumHydrogens", PropertyKind::UInt16),
        0x0433 => ("GenericNickname", PropertyKind::String),
        0x0437 => ("AS", PropertyKind::Enum(ATOM_STEREO)),
        0x0439 => ("AtomNumber", PropertyKind::String),
        0x043B => ("ShowAtomStereo", PropertyKind::Boolean),
        0x043C => ("ShowAtomNumber", PropertyKind::Boolean),
        0x043F => ("IsotopicAbundance", PropertyKind::Enum8(ISOTOPIC_ABUNDANCE)),
        0x0444 => ("HideImplicitHydrogens", PropertyKind::Boolean),
        0x0445 => ("ShowAtomEnhancedStereo", PropertyKind::Boolean),
        0x0504 => ("Weight", PropertyKind::Float64),
        0x0505 => ("ConnectionOrder", PropertyKind::ObjectIdArray),
        0x0600 => ("Order", PropertyKind::BondOrder),
        0x0601 => ("Display", PropertyKind::Enum(BOND_DISPLAY)),
        0x0602 => ("Display2", PropertyKind::Enum(BOND_DISPLAY)),
        0x0603 => ("DoublePosition", PropertyKind::Enum(DOUBLE_POSITION)),
        0x0604 => ("B", PropertyKind::UInt32),
        0x0605 => ("E", PropertyKind::UInt32),
        0x0608 => ("BeginAttach", PropertyKind::UInt8),
        0x0609 => ("EndAttach", PropertyKind::UInt8),
        0x060A => ("BS", PropertyKind::Enum(BOND_STEREO)),
        0x060B => ("BondCircularOrdering", PropertyKind::ObjectIdArray),
        0x060E => ("CrossingBonds", PropertyKind::ObjectIdArray),
        0x0701 => ("Justification", PropertyKind::Enum8(JUSTIFICATION)),
        0x0702 => ("LineHeight", PropertyKind::LineHeightUInt16),
        0x0703 => ("WordWrapWidth", PropertyKind::Int16),
        0x0704 => ("LineStarts", PropertyKind::Int16ListWithCounts),
        0x0705 => ("LabelAlignment", PropertyKind::Enum8(LABEL_ALIGNMENT)),
        0x0706 => ("LabelLineHeight", PropertyKind::LineHeightInt16),
        0x0707 => ("CaptionLineHeight", PropertyKind::LineHeightInt16),
        0x0708 => ("InterpretChemically", PropertyKind::Boolean),
        0x0709 => ("UTF8Text", PropertyKind::String),
        0x0802 => ("PrintMargins", PropertyKind::Rectangle),
        0x0803 => ("ChainAngle", PropertyKind::Fixed16_16),
        0x0804 => ("BondSpacing", PropertyKind::BondSpacing),
        0x0805 => ("BondLength", PropertyKind::Coordinate),
        0x0806 => ("BoldWidth", PropertyKind::Coordinate),
        0x0807 => ("LineWidth", PropertyKind::Coordinate),
        0x0808 => ("MarginWidth", PropertyKind::Coordinate),
        0x0809 => ("HashSpacing", PropertyKind::Coordinate),
        0x080A => ("LabelStyle", PropertyKind::FontStyle),
        0x080B => ("CaptionStyle", PropertyKind::FontStyle),
        0x080C => ("CaptionJustification", PropertyKind::Enum8(JUSTIFICATION)),
        0x080D => ("FractionalWidths", PropertyKind::Boolean),
        0x080F => ("WidthPages", PropertyKind::UInt16),
        0x0810 => ("HeightPages", PropertyKind::UInt16),
        0x0812 => ("Width", PropertyKind::Coordinate),
        0x0813 => ("Height", PropertyKind::Coordinate),
        0x0815 => ("Header", PropertyKind::String),
        0x0816 => ("HeaderPosition", PropertyKind::Coordinate),
        0x0817 => ("Footer", PropertyKind::String),
        0x0818 => ("FooterPosition", PropertyKind::Coordinate),
        0x0819 => ("PrintTrimMarks", PropertyKind::BooleanImplied),
        0x081A => ("LabelFont", PropertyKind::Int16),
        0x081B => ("CaptionFont", PropertyKind::Int16),
        0x081C => ("LabelSize", PropertyKind::Int16),
        0x081D => ("CaptionSize", PropertyKind::Int16),
        0x081E => ("LabelFace", PropertyKind::Int16),
        0x081F => ("CaptionFace", PropertyKind::Int16),
        0x0822 => ("BondSpacingAbs", PropertyKind::Coordinate),
        0x0823 => ("LabelJustification", PropertyKind::Enum8(JUSTIFICATION)),
        0x0900 => ("WindowIsZoomed", PropertyKind::BooleanImplied),
        0x0901 => ("WindowPosition", PropertyKind::Point2D),
        0x0902 => ("WindowSize", PropertyKind::Point2D),
        0x0A00 => ("GraphicType", PropertyKind::Enum(GRAPHIC_TYPE)),
        0x0A01 => ("LineType", PropertyKind::BitFlags(LINE_TYPE)),
        0x0A02 => ("ArrowType", PropertyKind::BitFlags(ARROW_TYPE)),
        0x0A03 => ("RectangleType", PropertyKind::BitFlags(RECTANGLE_TYPE)),
        0x0A04 => ("OvalType", PropertyKind::BitFlags(OVAL_TYPE)),
        0x0A05 => ("OrbitalType", PropertyKind::Enum(ORBITAL_TYPE)),
        0x0A06 => ("BracketType", PropertyKind::Enum(BRACKET_TYPE)),
        0x0A07 => ("SymbolType", PropertyKind::Enum(SYMBOL_TYPE)),
        0x0A20 => ("HeadSize", PropertyKind::Int16),
        0x0A21 => ("AngularSize", PropertyKind::AngleTenths),
        0x0A22 => ("LipSize", PropertyKind::Int16),
        0x0A27 => ("BracketedObjectIDs", PropertyKind::ObjectIdArray),
        0x0A28 => ("RepeatCount", PropertyKind::Float64),
        0x0A2B => ("GraphicID", PropertyKind::UInt32),
        0x0A2F => ("ArrowheadType", PropertyKind::Enum(ARROW_HEAD_TYPE)),
        0x0A30 => ("ArrowheadCenterSize", PropertyKind::UInt16),
        0x0A31 => ("ArrowheadWidth", PropertyKind::UInt16),
        0x0A33 => ("ArrowShaftSpacing", PropertyKind::UInt16),
        0x0A34 => ("ArrowEquilibriumRatio", PropertyKind::UInt16),
        0x0A35 => ("ArrowheadHead", PropertyKind::Enum(ARROW_HEAD_POSITION)),
        0x0A36 => ("ArrowheadTail", PropertyKind::Enum(ARROW_HEAD_POSITION)),
        0x0A37 => ("FillType", PropertyKind::Enum(FILL_TYPE)),
        0x0A38 => ("CurveSpacing", PropertyKind::UInt16),
        0x0A39 => ("Closed", PropertyKind::BooleanImplied),
        0x0A3A => ("Dipole", PropertyKind::BooleanImplied),
        0x0A3B => ("NoGo", PropertyKind::Enum8(NO_GO)),
        0x0A3C => ("CornerRadius", PropertyKind::Int16),
        0x0A3E => ("ArrowSource", PropertyKind::UInt16),
        0x0A3F => ("ArrowTarget", PropertyKind::UInt16),
        0x0A60 => ("Edition", PropertyKind::Binary),
        0x0A61 => ("EditionAlias", PropertyKind::Binary),
        0x0A62 => ("MacPICT", PropertyKind::Binary),
        0x0A63 => ("WindowsMetafile", PropertyKind::Binary),
        0x0A64 => ("OLEObject", PropertyKind::Binary),
        0x0A65 => ("EnhancedMetafile", PropertyKind::Binary),
        0x0A6E => ("GIF", PropertyKind::Binary),
        0x0A6F => ("TIFF", PropertyKind::Binary),
        0x0A70 => ("PNG", PropertyKind::Binary),
        0x0A71 => ("JPEG", PropertyKind::Binary),
        0x0A72 => ("BMP", PropertyKind::Binary),
        0x0AB1 => ("Tail", PropertyKind::Coordinate),
        0x0B00 => ("TextFrame", PropertyKind::Rectangle),
        0x0B80 => ("GeometricFeature", PropertyKind::Int8),
        0x0B81 => ("RelationValue", PropertyKind::Float64),
        0x0B82 => ("BasisObjects", PropertyKind::ObjectIdArray),
        0x0B83 => ("ConstraintType", PropertyKind::Int8),
        0x0D06 => ("PositioningType", PropertyKind::Enum8(POSITIONING_TYPE)),
        0x0D07 => ("PositioningAngle", PropertyKind::Fixed16_16),
        0x0D08 => ("PositioningOffset", PropertyKind::Point2D),
        _ => return None,
    };
    Some(PropertySchema {
        name: schema.0,
        kind: schema.1,
    })
}

pub(super) fn property_tag(name: &str) -> Option<u16> {
    Some(match name {
        "CreationUserName" => 0x0001,
        "CreationProgram" => 0x0003,
        "ModificationUserName" => 0x0004,
        "ModificationProgram" => 0x0006,
        "Name" => 0x0008,
        "Comment" => 0x0009,
        "Z" => 0x000A,
        "Visible" => 0x0011,
        "SupersededBy" => 0x0012,
        "p" => 0x0200,
        "xyz" => 0x0201,
        "extent" => 0x0202,
        "BoundingBox" => 0x0204,
        "RotationAngle" => 0x0205,
        "Head3D" => 0x0207,
        "Tail3D" => 0x0208,
        "TopLeft" => 0x0209,
        "TopRight" => 0x020A,
        "BottomRight" => 0x020B,
        "BottomLeft" => 0x020C,
        "Center3D" => 0x020D,
        "MajorAxisEnd3D" => 0x020E,
        "MinorAxisEnd3D" => 0x020F,
        "color" => 0x0301,
        "bgcolor" => 0x0302,
        "NodeType" => 0x0400,
        "LabelDisplay" => 0x0401,
        "Element" => 0x0402,
        "Isotope" => 0x0420,
        "Charge" => 0x0421,
        "Radical" => 0x0422,
        "ImplicitHydrogens" => 0x0424,
        "NumHydrogens" => 0x042B,
        "AS" => 0x0437,
        "AtomNumber" => 0x0439,
        "ShowAtomStereo" => 0x043B,
        "ShowAtomNumber" => 0x043C,
        "IsotopicAbundance" => 0x043F,
        "HideImplicitHydrogens" => 0x0444,
        "ShowAtomEnhancedStereo" => 0x0445,
        "Order" => 0x0600,
        "Display" => 0x0601,
        "Display2" => 0x0602,
        "DoublePosition" => 0x0603,
        "B" => 0x0604,
        "E" => 0x0605,
        "BeginAttach" => 0x0608,
        "EndAttach" => 0x0609,
        "BS" => 0x060A,
        "BondCircularOrdering" => 0x060B,
        "GenericNickname" => 0x0433,
        "ConnectionOrder" => 0x0505,
        "CrossingBonds" => 0x060E,
        "Justification" => 0x0701,
        "LineHeight" => 0x0702,
        "WordWrapWidth" => 0x0703,
        "LineStarts" => 0x0704,
        "LabelAlignment" => 0x0705,
        "LabelLineHeight" => 0x0706,
        "CaptionLineHeight" => 0x0707,
        "InterpretChemically" => 0x0708,
        "UTF8Text" => 0x0709,
        "PrintMargins" => 0x0802,
        "ChainAngle" => 0x0803,
        "BondSpacing" => 0x0804,
        "BondLength" => 0x0805,
        "BoldWidth" => 0x0806,
        "LineWidth" => 0x0807,
        "MarginWidth" => 0x0808,
        "HashSpacing" => 0x0809,
        "CaptionJustification" => 0x080C,
        "FractionalWidths" => 0x080D,
        "WidthPages" => 0x080F,
        "HeightPages" => 0x0810,
        "Width" => 0x0812,
        "Height" => 0x0813,
        "Header" => 0x0815,
        "HeaderPosition" => 0x0816,
        "Footer" => 0x0817,
        "FooterPosition" => 0x0818,
        "PrintTrimMarks" => 0x0819,
        "LabelFont" => 0x081A,
        "CaptionFont" => 0x081B,
        "LabelSize" => 0x081C,
        "CaptionSize" => 0x081D,
        "LabelFace" => 0x081E,
        "CaptionFace" => 0x081F,
        "BondSpacingAbs" => 0x0822,
        "LabelJustification" => 0x0823,
        "WindowIsZoomed" => 0x0900,
        "WindowPosition" => 0x0901,
        "WindowSize" => 0x0902,
        "GraphicType" => 0x0A00,
        "LineType" => 0x0A01,
        "ArrowType" => 0x0A02,
        "RectangleType" => 0x0A03,
        "OvalType" => 0x0A04,
        "OrbitalType" => 0x0A05,
        "BracketType" => 0x0A06,
        "SymbolType" => 0x0A07,
        "HeadSize" => 0x0A20,
        "AngularSize" => 0x0A21,
        "LipSize" => 0x0A22,
        "BracketedObjectIDs" => 0x0A27,
        "GraphicID" => 0x0A2B,
        "ArrowheadType" => 0x0A2F,
        "ArrowheadCenterSize" => 0x0A30,
        "ArrowheadWidth" => 0x0A31,
        "ArrowShaftSpacing" => 0x0A33,
        "ArrowEquilibriumRatio" => 0x0A34,
        "ArrowheadHead" => 0x0A35,
        "ArrowheadTail" => 0x0A36,
        "FillType" => 0x0A37,
        "CurveSpacing" => 0x0A38,
        "Closed" => 0x0A39,
        "Dipole" => 0x0A3A,
        "NoGo" => 0x0A3B,
        "CornerRadius" => 0x0A3C,
        "ArrowSource" => 0x0A3E,
        "ArrowTarget" => 0x0A3F,
        "Tail" => 0x0AB1,
        "TextFrame" => 0x0B00,
        "GeometricFeature" => 0x0B80,
        "RelationValue" => 0x0B81,
        "BasisObjects" => 0x0B82,
        "ConstraintType" => 0x0B83,
        "PositioningType" => 0x0D06,
        "PositioningAngle" => 0x0D07,
        "PositioningOffset" => 0x0D08,
        _ => return None,
    })
}

pub(super) fn encode_property(name: &str, value: &str) -> Option<(u16, Vec<u8>)> {
    let (tag, official_type) = match property_tag(name) {
        Some(tag) => (tag, None),
        None => {
            let (tag, kind) = official_property_tag_and_type(name)?;
            (tag, Some(kind))
        }
    };
    let Some(schema) = property_schema(tag) else {
        return Some((
            tag,
            encode_official_lexical(official_type.as_deref()?, value)?,
        ));
    };
    let bytes = match schema.kind {
        PropertyKind::String => encode_plain_cdx_string(value),
        PropertyKind::Binary => decode_hex_bytes(value)?,
        PropertyKind::Point2D => encode_point2d(value)?,
        PropertyKind::Point3D => encode_point3d(value)?,
        PropertyKind::Rectangle => encode_rectangle(value)?,
        PropertyKind::Coordinate => encode_coordinate(value)?,
        PropertyKind::Int8 => vec![value.parse::<i8>().ok()? as u8],
        PropertyKind::UInt8 => vec![value.parse::<u8>().ok()?],
        PropertyKind::Int16 => value.parse::<i16>().ok()?.to_le_bytes().to_vec(),
        PropertyKind::UInt16 => value.parse::<u16>().ok()?.to_le_bytes().to_vec(),
        PropertyKind::LineHeightInt16 => encode_line_height(value, false)?,
        PropertyKind::LineHeightUInt16 => encode_line_height(value, true)?,
        PropertyKind::Fixed16_16 => ((value.parse::<f64>().ok()? * 65536.0).round() as i32)
            .to_le_bytes()
            .to_vec(),
        PropertyKind::UInt32 => value.parse::<u32>().ok()?.to_le_bytes().to_vec(),
        PropertyKind::Float64 => value.parse::<f64>().ok()?.to_le_bytes().to_vec(),
        PropertyKind::Boolean => vec![if yes(value) { 1 } else { 0 }],
        PropertyKind::BooleanImplied => {
            if yes(value) {
                Vec::new()
            } else {
                return None;
            }
        }
        PropertyKind::BondOrder => encode_bond_order(value)?,
        PropertyKind::BondSpacing => ((value.parse::<f64>().ok()? * 10.0).round() as i16)
            .to_le_bytes()
            .to_vec(),
        PropertyKind::AngleTenths => ((value.parse::<f64>().ok()? * 10.0).round() as i16)
            .to_le_bytes()
            .to_vec(),
        PropertyKind::FontStyle => return None,
        PropertyKind::ObjectIdArray => encode_u32_array(value)?,
        PropertyKind::Int16ListWithCounts => encode_i16_counted_list(value)?,
        PropertyKind::Enum8(values) => vec![enum_value(value, values)? as i8 as u8],
        PropertyKind::Enum(values) => enum_value(value, values)?.to_le_bytes().to_vec(),
        PropertyKind::BitFlags(values) => encode_bit_flags(value, values)?.to_le_bytes().to_vec(),
    };
    Some((tag, bytes))
}

pub(super) fn object_name(tag: u16) -> Option<&'static str> {
    Some(match tag {
        0x8000 => "CDXML",
        0x8001 => "page",
        0x8002 => "group",
        0x8003 => "fragment",
        0x8004 => "n",
        0x8005 => "b",
        0x8006 => "t",
        0x8007 => "graphic",
        0x8008 => "curve",
        0x8009 => "embeddedobject",
        0x800A => "altgroup",
        0x800B => "templategrid",
        0x800C => "regnum",
        0x800D => "scheme",
        0x800E => "step",
        0x8010 => "spectrum",
        0x8011 => "objecttag",
        0x8013 => "sequence",
        0x8014 => "crossreference",
        0x8015 => "splitter",
        0x8016 => "table",
        0x8017 => "bracketedgroup",
        0x8018 => "bracketattachment",
        0x8019 => "crossingbond",
        0x8020 => "border",
        0x8021 => "geometry",
        0x8022 => "constraint",
        0x8023 => "tlcplate",
        0x8024 => "tlclane",
        0x8025 => "tlcspot",
        0x8026 => "chemicalproperty",
        0x8027 => "arrow",
        _ => return None,
    })
}

pub(super) fn legacy_chemsema_object_name(tag: u16) -> Option<&'static str> {
    Some(match tag {
        0x801B => "geometry",
        0x801C => "constraint",
        0x801D => "tlcplate",
        0x801E => "tlclane",
        0x801F => "tlcspot",
        0x8020 => "chemicalproperty",
        0x8021 => "arrow",
        0x8025 => "bioshape",
        0x802A => "border",
        0x802B => "annotation",
        _ => return None,
    })
}

pub(super) fn object_tag(name: &str) -> Option<u16> {
    Some(match name {
        "CDXML" => 0x8000,
        "page" => 0x8001,
        "group" => 0x8002,
        "fragment" => 0x8003,
        "n" => 0x8004,
        "b" => 0x8005,
        "t" => 0x8006,
        "graphic" => 0x8007,
        "curve" => 0x8008,
        "embeddedobject" => 0x8009,
        "altgroup" => 0x800A,
        "templategrid" => 0x800B,
        "regnum" => 0x800C,
        "scheme" => 0x800D,
        "step" => 0x800E,
        "spectrum" => 0x8010,
        "objecttag" => 0x8011,
        "sequence" => 0x8013,
        "crossreference" => 0x8014,
        "splitter" => 0x8015,
        "table" => 0x8016,
        "bracketedgroup" => 0x8017,
        "bracketattachment" => 0x8018,
        "crossingbond" => 0x8019,
        "geometry" => 0x801B,
        "constraint" => 0x801C,
        "tlcplate" => 0x801D,
        "tlclane" => 0x801E,
        "tlcspot" => 0x801F,
        "chemicalproperty" => 0x8020,
        "arrow" => 0x8021,
        "border" => 0x802A,
        _ => return None,
    })
}

pub(super) fn is_object_tag(tag: u16) -> bool {
    tag & 0x8000 != 0
}
